### PR TITLE
Make DropdownDivConverter compatible with Mx 6.10

### PR DESCRIPTION
**Pull request by reinouts**
- Allow passing non-persistent entities
- prevent javascript exception about calling close on undefined by using mx.ui.action instead of mx.data.action

### CODE REVIEW

**Comment by JelteMX** [comment]
Thanks @reinouts, this resolved by @WillemUXMendix. I also did some cleanup in [this commit](https://github.com/mendix/DropdownDivConverter/pull/11/commits/92c4e30fc1b7a5bf0bb0c6369ff65639a37c5b17#diff-e252e76df6221272032f94d486b9cd9eR192). Will let Willem merge the other PR

**Comment by reinouts** [comment]
@JelteMX I noticed that [`allowNonPersistableEntities="true"`](https://github.com/mendix/DropdownDivConverter/pull/10/files#diff-5e3de3d1cf54654c8e4bfc95ec90e8f5R81) wasn't included in @WillemUXMendix 's commit. We do need this!

**Comment by JelteMX** [comment]
That is included [here](https://github.com/mendix/DropdownDivConverter/blob/master/src/DropdownDivConverter/DropdownDivConverter.xml#L64), this should be enough, right?

**Comment by reinouts** [comment]
OK, sorry, must have overlooked it.

**Pull request closed without merging**
